Fixed MainActivity, added TimerService and TimerServiceImpl
ohhimate/KateSudy pull request #3
Opened 2022-01-10 14:02 UTC by caitlykate

2022-01-12 09:47 UTC, ohhimate requested changes

2022-01-12 09:47 UTC, ohhimate commented on app/src/main/java/team/mediasoft/katestudy/splash/data/service/TimerServiceImpl.kt
> +            }
После цикла нужно вызвать onComplete()

2022-01-12 16:51 UTC, ohhimate requested changes

2022-01-12 16:51 UTC, ohhimate commented on app/src/main/java/team/mediasoft/katestudy/splash/presentation/repository/TimerRepository.kt
> +    fun getReactiveTimer(): LiveData<Int> {
Репозиторий должен отдавать рхДжаву

2022-01-12 16:51 UTC, ohhimate commented on app/src/main/java/team/mediasoft/katestudy/splash/presentation/repository/TimerRepository.kt
> +                .toFlowable(BackpressureStrategy.BUFFER)
Зачем это? Словила бэкпрешур? Если да, можно сразу фловабл отдавать

2022-01-12 16:51 UTC, ohhimate commented on app/src/main/java/team/mediasoft/katestudy/splash/presentation/repository/TimerRepository.kt
> +    fun getReactiveTimer(): LiveData<Int> {
а уже во вьюмодели ты будешь дергать две разные лайвдаты: на новое число таймера и на onComplete()

2022-01-12 16:51 UTC, ohhimate commented on app/src/main/java/team/mediasoft/katestudy/splash/presentation/presenter/TimerViewModel.kt
> +    fun getTimer(): LiveData<Int> {
Я бы сделал так: у тебя наружу торчат две лайвдаты, которые ты дергаешь, когда приходит онНекст/онКомплит. Ты отдельно на них подписываешься и отдельно стартуешь таймер, когда стартуешь активность. Это все потому что тебе нужно перехватить вызов onComplete(), а я не знаю способа сделать это по-другому. Если найдешь - маякуй.

2022-01-12 16:51 UTC, ohhimate commented on app/src/main/java/team/mediasoft/katestudy/baseapp/presentation/activity/BaseActivity.kt
> +        Log.d(TEST_TAG, this.javaClass.simpleName + ".onCreate")
А это зачем?

2022-01-13 10:54 UTC, caitlykate commented on app/src/main/java/team/mediasoft/katestudy/baseapp/presentation/activity/BaseActivity.kt
> +        Log.d(TEST_TAG, this.javaClass.simpleName + ".onCreate")
чтобы отфильтровать все свои логи по одному тэгу

2022-01-17 09:16 UTC, ohhimate approved these changes

2022-01-17 09:16 UTC, ohhimate commented on app/src/main/java/team/mediasoft/katestudy/splash/presentation/activity/SplashScreenActivity.kt
> +        //подписываемся на ЛД
выноси такое в отдельные методы, в некст пр-е

2022-01-17 09:16 UTC, ohhimate commented on app/src/main/java/team/mediasoft/katestudy/splash/presentation/presenter/TimerViewModel.kt
> +        subscribeToTimer()
Этот метод должен вызываться из активности

2022-01-17 09:16 UTC, merged